format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#33658A)\
$git_branch\
$git_status\
[](fg:#33658A bg:#86BBD8)\
$c\
$golang\
$nodejs\
$rust\
[](fg:#86BBD8)\
$line_break$character"""

[username]
show_always = true
style_user = "bg:#9A348E fg:#0E1011"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#DA627D fg:#0E1011"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Shorthand for long paths
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#86BBD8 fg:#0E1011"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A fg:#0E1011"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#33658A fg:#0E1011"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#33658A fg:#0E1011"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8 fg:#0E1011"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#0E1011"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#0E1011"
format = '[ $symbol ($version) ]($style)'
